services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--entrypoints.websecure.address=:443"
      # Dynamic configuration file for certs
      - "--providers.file.filename=/etc/traefik/dynamic/certs-config.yaml"
      # Docker configuration
      - "--providers.docker" # Enable Docker provider
      - "--providers.docker.exposedbydefault=false" # Disable exposing all containers by default
      - "--providers.docker.network=traefik-network" # Use the traefik network
      - "--providers.docker.endpoint=unix:///var/run/docker.sock" # Docker socket
    ports:
      - "443:443"
    volumes:
      # Docker socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Certs dynamic config
      - /dockerdata/traefik/certs/certs-config.yaml:/etc/traefik/dynamic/certs-config.yaml:ro
      # Certs dir
      - /dockerdata/traefik/certs:/etc/traefik/certs
    networks:
      - traefik-network
    restart: always

networks:
  traefik-network:
    external: true
